### ISSUE TITLE
Failed to process audio

### ISSUE THREAD

**Issue by RandomHuang** [xuegao-tzx/whisper_flutter_new#4]
Use flutter_sound record (Codec.pcm16WAV) in iOS, file exist.

flutter: file length 4096
flutter: Use existing model base
flutter: Result =  {@type: version, message: lib version: v1.0.1}
flutter: lib version: v1.0.1
flutter: Use existing model base
flutter: Result =  {@type: error, message: failed to process audio}
flutter: Transcribe request {@type: error, message: failed to process audio}
[Global Loggy] ‼️ 18:32:37.269840 - Exception: failed to process audio
               #0      Whisper.transcribe (package:whisper_flutter_new/whisper_flutter_new.dart:119:7)
<asynchronous suspension>
#1      _TestP...
[Global Loggy] ‼️ 18:32:37.270162 - error stack #0      Whisper.transcribe (package:whisper_flutter_new/whisper_flutter_new.dart:119:7)
<asynchronous suspension>
#1      _TestPageState.translate (package:ai_record/page/test/test_page.dart:81:48)
<asynchronous suspension>

flutter: Transcribe Exception failed to process audio

**Comment by RandomHuang** [comment]
Change to tiny model still have same problem 

flutter: file length 4096
flutter: Download model tiny
flutter: Download Down . Path = /var/mobile/Containers/Data/Application/AADDB388-1A36-43AF-A066-B260E14EBF44/Library/ggml-tiny.bin
flutter: Result =  {@type: version, message: lib version: v1.0.1}
flutter: lib version: v1.0.1
flutter: Use existing model tiny
flutter: Result =  {@type: error, message: failed to process audio}
flutter: Transcribe request {@type: error, message: failed to process audio}
[Global Loggy] ‼️ 18:36:25.321926 - Exception: failed to process audio
flutter: Transcribe Exception failed to process audio
               #0      Whisper.transcribe (package:whisper_flutter_new/whisper_flutter_new.dart:119:7)
<asynchronous suspension>
#1      _TestP...
[Global Loggy] ‼️ 18:36:25.322299 - error stack #0      Whisper.transcribe (package:whisper_flutter_new/whisper_flutter_new.dart:119:7)
<asynchronous suspension>
#1      _TestPageState.translate (package:ai_record/page/test/test_page.dart:81:48)
<asynchronous suspension>

[ERROR:flutter/shell/platform/darwin/ios/framework/Source/profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument

**Comment by xuegao-tzx** [comment]
This model only supports 16-bit WAV files.
![image](https://github.com/user-attachments/assets/a13c2adb-0300-4de7-94c3-2d2bc2784f61)

You can also try running the sample code to see if the problem can be reproduced.

**Comment by RandomHuang** [comment]
thanks reply.
I have already used the pcm16WAV format from flutter_sound for recording, and its documentation says 'Linear 16 PCM, which is a Wave file.' Could you recommend any Flutter plugins for recording? Thank you

**Comment by xuegao-tzx** [comment]
I use record to record, and use ffmpeg_kit_flutter_full_gpl to convert. There is no better way at present. If you have one, please tell me. Thank you very much.

**Comment by xmanatee** [comment]
Can confirm that record works. I use it with whisper supported config and it seems to work out of the box on ios and macos:
```
    await _recorder!.start(
      const RecordConfig(
        encoder: AudioEncoder.pcm16bits,
        sampleRate: 16000,
        numChannels: 1,
        autoGain: true,
        echoCancel: true,
        noiseSuppress: true,
      ),
      path: chunkPath,
    );
```

On Android however it turned the output WAV file is missing the header, so I'm adding the header manually:
```
  Future<void> addWavHeader(
    final String rawPcmPath, {
    final String? wavOutputFilePath,
  }) async {
    final wavFilePath = wavOutputFilePath ?? rawPcmPath;
    final rawPcmFile = File(rawPcmPath);
    final rawPcmData = await rawPcmFile.readAsBytes();

    // Recording settings
    const channels = 1;
    const sampleRate = 16000;
    const bitsPerSample = 16;
    const byteRate = sampleRate * channels * bitsPerSample ~/ 8;
    const blockAlign = channels * bitsPerSample ~/ 8;
    final subchunk2Size = rawPcmData.length;
    final chunkSize = 36 + subchunk2Size;

    final header = ByteData(44);
    var offset = 0;

    // ChunkID 'RIFF'
    header.setUint8(offset++, "R".codeUnitAt(0));
    header.setUint8(offset++, "I".codeUnitAt(0));
    header.setUint8(offset++, "F".codeUnitAt(0));
    header.setUint8(offset++, "F".codeUnitAt(0));

    // ChunkSize
    header.setUint32(offset, chunkSize, Endian.little);
    offset += 4;

    // Format 'WAVE'
    header.setUint8(offset++, "W".codeUnitAt(0));
    header.setUint8(offset++, "A".codeUnitAt(0));
    header.setUint8(offset++, "V".codeUnitAt(0));
    header.setUint8(offset++, "E".codeUnitAt(0));

    // Subchunk1ID 'fmt '
    header.setUint8(offset++, "f".codeUnitAt(0));
    header.setUint8(offset++, "m".codeUnitAt(0));
    header.setUint8(offset++, "t".codeUnitAt(0));
    header.setUint8(offset++, " ".codeUnitAt(0));

    // Subchunk1Size (16 for PCM)
    header.setUint32(offset, 16, Endian.little);
    offset += 4;

    // AudioFormat (1 for PCM)
    header.setUint16(offset, 1, Endian.little);
    offset += 2;

    // NumChannels
    header.setUint16(offset, channels, Endian.little);
    offset += 2;

    // SampleRate
    header.setUint32(offset, sampleRate, Endian.little);
    offset += 4;

    // ByteRate
    header.setUint32(offset, byteRate, Endian.little);
    offset += 4;

    // BlockAlign
    header.setUint16(offset, blockAlign, Endian.little);
    offset += 2;

    // BitsPerSample
    header.setUint16(offset, bitsPerSample, Endian.little);
    offset += 2;

    // Subchunk2ID 'data'
    header.setUint8(offset++, "d".codeUnitAt(0));
    header.setUint8(offset++, "a".codeUnitAt(0));
    header.setUint8(offset++, "t".codeUnitAt(0));
    header.setUint8(offset++, "a".codeUnitAt(0));

    // Subchunk2Size
    header.setUint32(offset, subchunk2Size, Endian.little);
    offset += 4;

    // Combine header and raw PCM data
    final wavData = BytesBuilder();
    wavData.add(header.buffer.asUint8List());
    wavData.add(rawPcmData);

    // Save the new WAV file
    final wavFile = File(wavFilePath);
    await wavFile.writeAsBytes(wavData.toBytes());
  }
```

This way I managed to avoid using ffmpeg completely (because iiuc ffmpeg only supports ui isolate which doesn't work for me).

Tested on iPad (m2), Macbook Pro (Intel i7) and Pixel 7.
